openapi: 3.1.0
info:
  title: DKIM Registry API
  description: |-
    This is the API specification for the DKIM Registry API, which follows the OpenAPI 3.0.3 specification.
  version: '0.1'
  license:
    name: MIT
    url: https://opensource.org/license/MIT
servers:
  - url: https://registry.prove.email/api
  - url: /api
    description: Development
paths:
  /key:
    get:
      tags:
        - dkim-key
      summary: List DKIM keys
      description: >
        Returns a list of DKIM keys for a given domain or domain suffix.
        The endpoint is rate limited to 5 requests per 10 seconds.
      operationId: listKeys
      parameters:
        - name: domain
          in: query
          description: Match the domain name and any subdomains.
          required: true
          schema:
            type: string
          example: 'example.com'
      responses:
        '400':
          description: Missing parameter
        '429':
          description: Rate limit exceeded
        '500':
          description: Unexpected error
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DkimKey'
  /dsp:
    post:
      tags:
        - domain-selector-pair
      summary: Add a domain/selector pair
      description: >
        Add a domain/selector pair.
        The server will try to fetch the DKIM key for the given domain and selector.
        If the key is found, the domain/selector pair will be added to the registry along with the key.
        The response indicates whether the domain/selector pair and the key were added to the registry, via the `added` field.
      operationId: addDsp
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DomainSelectorPair'
      responses:
        '201':
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                required:
                  - added
                  - message
                properties:
                  added:
                    type: boolean
                    description: Whether the domain/selector pair was added to the registry
                  message:
                    $ref: '#/components/schemas/DomainSelectorPair'

        '400':
          description: Invalid input
        '500':
          description: Unexpected error
  /domains/{name}:
    get:
      tags:
        - dkim-key
      summary: List DKIM keys
      description: Returns a list of DKIM keys for a given domain or domain suffix
      operationId: listDomains
      deprecated: true
      parameters:
        - name: name
          in: path
          description: Match the domain name and any subdomains.
          required: true
          schema:
            type: string
          example: 'example.com'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DkimKey'
        '429':
          description: Rate limit exceeded
        '500':
          description: Unexpected error
components:
  schemas:
    DkimKey:
      type: object
      required:
        - value
        - domain
        - selector
      properties:
        value:
          type: string
          examples:
            - k=rsa; t=s; p=MIGfMA0GCSqGSIb3D...
        domain:
          type: string
          examples:
            - example.com
        selector:
          type: string
          examples:
            - dkimkey
        firstSeenAt:
          type: string
          format: date-time
          examples:
            - 2021-01-01T00:00:00Z
        lastSeenAt:
          type: string
          format: date-time
          examples:
            - 2021-01-01T00:00:00Z
    DomainSelectorPair:
      type: object
      required:
        - domain
        - selector
      properties:
        domain:
          type: string
          examples:
            - example.com
        selector:
          type: string
          examples:
            - s1
